### PR TITLE
updating sdk vesion

### PR DESCRIPTION
**Pull request by specialtactics**
Updating SDK version to 2.1.1

Can you please merge & tag?

### CODE REVIEW

**Comment by specialtactics** [comment]
@Jean85 Composer doesn't work like that, this package locks sentry/sentry to version 2.0.1; `sentry/sentry": "^2.0.1",` - so you cannot just update composer (with either command you suggested) and get an updated sentry 2.1.x. If you don't believe me - feel free to try yourself.

So far as this package, as far as I understand, you could either allow any version 2, by specifying "^2" - in which case your suggestion actually would work - or, you need to update the version and tag it every time the sentry/sentry package updates to keep it consistent, and then people can choose which version they want in their composer file.

Since you have locked the version down to such an extent in this package's composer file, I assumed you have gone for the latter approach.

Please advise.

**Comment by Jean85** [comment]
Sorry @specialtactics but you're mistaken. The behavior you're describing is related to the `~` operator, not the `^`, which is used to follow SemVer. You can check it out here: https://semver.mwl.be/#!?package=sentry%2Fsentry&version=%5E2.0.1&minimum-stability=stable

Also, you should try the suggested commands, and do `composer why-not sentry/sentry:2.1 if that isn't enough: you may have other constraints that are impeding the upgrade.

**Comment by archon810** [comment]
We're upgrading to v2 of sentry and doing this works fine:
`composer.phar require sentry/sentry php-http/curl-client guzzlehttp/psr7`

But doing this does not:
`composer.phar require sentry/sdk`

```
Using version ^2.0 for sentry/sdk
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - sentry/sdk 2.0.3 requires sentry/sentry ^2.0.1 -> satisfiable by sentry/sentry[2.0.1, 2.1.0, 2.1.1, 2.1.x-dev, 2.2.x-dev] but these conflict with your requirements or minimum-stability.
    - sentry/sdk 2.0.2 requires sentry/sentry ^2.0.1 -> satisfiable by sentry/sentry[2.0.1, 2.1.0, 2.1.1, 2.1.x-dev, 2.2.x-dev] but these conflict with your requirements or minimum-stability.
    - sentry/sdk 2.0.1 requires sentry/sentry ^2.0 -> satisfiable by sentry/sentry[2.0.0, 2.0.0-beta1, 2.0.0-beta2, 2.0.1, 2.1.0, 2.1.1, 2.1.x-dev, 2.2.x-dev] but these conflict with your requirements or minimum-stability.
    - sentry/sdk 2.0.0 requires sentry/sentry ^2.0 -> satisfiable by sentry/sentry[2.0.0, 2.0.0-beta1, 2.0.0-beta2, 2.0.1, 2.1.0, 2.1.1, 2.1.x-dev, 2.2.x-dev] but these conflict with your requirements or minimum-stability.
    - Installation request for sentry/sdk ^2.0 -> satisfiable by sentry/sdk[2.0.0, 2.0.1, 2.0.2, 2.0.3].


Installation failed, reverting ./composer.json to its original content.
```

Any idea why this would be?

**Comment by archon810** [comment]
OK, I figured it out. First, I needed to remove "sentry/sentry": "1.10.0" and composer update.

Then this sdk install worked and it installed sentry 2.1.1 and all the deps, with the only entry in composer.json being "sentry/sdk": "^2.0"

I both like and dislike this. On one hand, all the deps are maintained outside of our own composer.json. On the other, it automatically updates sentry versions and doesn't let us lock them in. What if something breaks? We could be potentially stuck with a broken sentry when we run composer update in the future.

**Comment by Jean85** [comment]
You can still lock the dependencies, you could've replace `"sentry/sentry": "1.10.0"` with `"sentry/sentry": "2.1"` or whatever. The only issue that you were having was a constraint that was not compatible with the requested update.

In my case I even replace the suggested deps like this when requiring the Symfony integration, hijacking the sdk package which is required underneath:
```
{
    "require": {
        "guzzlehttp/guzzle": "^6.3.3",
        "guzzlehttp/promises": "^1.3.1",
        "guzzlehttp/psr7": "^1.6",
        "php-http/guzzle6-adapter": "^2.0",
        "sentry/sentry": "^2.1",
        "sentry/sentry-symfony": "^3.1",
    },
    "replace": {
        "sentry/sdk": "*",
    }
}
```

**Comment by archon810** [comment]
Thank you, this is a great solution.

`composer.phar` require sentry/sdk sentry/sentry:2.1.1`

**Comment by Jean85** [comment]
@cgsmith please maintain a civil tone.

That is the proper usage of Composer for overriding a package. If you want, you can skip the metapackage altogether and require the dependency directly, as documented in the readme: https://github.com/getsentry/sentry-php#install

```bash
php composer.phar require sentry/sentry php-http/curl-client guzzlehttp/psr7
```

or, in `composer.json`, just removing the replace and the require for `sentry/sdk`:
```json
{
    "require": {
        "guzzlehttp/guzzle": "^6.3.3",
        "guzzlehttp/promises": "^1.3.1",
        "guzzlehttp/psr7": "^1.6",
        "php-http/guzzle6-adapter": "^2.0",
        "sentry/sentry": "^2.1",
        "sentry/sentry-symfony": "^3.1",
    }
}
```

**Comment by Jean85** [comment]
No it's not. The metapackage is a "quick start" solution, that gives you all the needed dependencies, suggesting a transport if you don't care which one is used underneath. The fact that it doesn't apply to your workflow doesn't mean it's pointless. It's currently [installed 10k times a day](https://packagist.org/packages/sentry/sdk/stats), which is [1/3 of the 2.x total installs](https://packagist.org/packages/sentry/sentry/stats) as of now.

Requiring the packages independently is instead useful if you want fine grain control over what transport is used; in my case I wanted to reuse Guzzle which was already required in my projects for other reasons.

**Pull request closed without merging**
